### ISSUE TITLE
ArithmeticException: / by zero

### ISSUE THREAD

**Issue by halszkaraptor** [thewibblywobbly/thirtysecondsnippets#7]
Sometimes the temp is zero because EchoNest may not have data on that song.

``` java
Exception in thread "LWJGL Application" java.lang.ArithmeticException: / by zero
    at com.gdp.thirtysecondsnippets.ThirtySecondSnippets.render(ThirtySecondSnippets.java:1548)
    at com.badlogic.gdx.Game.render(Game.java:46)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:215)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)
ons/gdx-audio/jni/libmpg123/parse.c:272] warning: TODO: finish lame version detetcion...
[/var/lib/hudson/jobs/libgdx/workspace/extensions/gdx-audio/jni/libmpg123/parse.c:272] warning: TODO: finish lame version detetcion...
```

**Comment by daaronin** [comment]
EchoNest is no longer part of project.
